import{a as h,i as d,S as m}from"./assets/vendor-b0d10f48.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(t){if(t.ep)return;t.ep=!0;const i=r(t);fetch(t.href,i)}})();document.querySelector(".search-form"),document.querySelector(".search-input"),document.querySelector(".search-btn"),document.querySelector(".images-list");function u(o){return!o||!o.hits?"":o.hits.map(e=>`<li class="images-list-item">
            <a class="img-link" href=${e.largeImageURL} onclick="event.preventDefault()"><img class="img" src=${e.webformatURL} alt=${e.tags}></img></a>
            <ul class="img-dscr">
                <li class="img-data">
                    <p class="img-data-title">Likes</p>
                    <p class="img-data-numbers">${e.likes}</p>
                </li>
                <li class="img-data">
                    <p class="img-data-title">Views</p>
                    <p class="img-data-numbers">${e.views}</p>
                </li>
                <li class="img-data">
                    <p class="img-data-title">Comments</p>
                    <p class="img-data-numbers">${e.comments}</p>
                </li>
                <li class="img-data">
                    <p class="img-data-title">Downloads</p>
                    <p class="img-data-numbers">${e.downloads}</p>
                </li>
            </ul>
        </li>`).join("")}async function p(o,e){const r="https://pixabay.com",s="/api/",t=new URLSearchParams({key:"44477511-7934322deb574a4a64d25451d",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}),i=`${r}${s}?${t}`,l={headers:{"Content-Type":"application/json"}};return(await h.get(i,{options:l})).data}const a={imageSearchForm:document.querySelector(".search-form"),imageSearchInput:document.querySelector(".search-input"),submitButton:document.querySelector(".search-btn"),imageList:document.querySelector(".images-list"),loader:document.querySelector(".loader"),loading:document.querySelector(".loading"),loadBtn:document.querySelector(".load-more-btn")};a.loader.style.display="none";let n=1,c=1;const f=15;let g;a.imageSearchForm.addEventListener("submit",async o=>{o.preventDefault();let e=o.target.elements.userData.value.trim();if(g=e,e==="")return a.imageList.innerHTML="",a.loader.style.display="none",d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight",transitionIn:"bounceInDown",transitionOut:"fadeOutDown"});a.loader.style.display="block",n=1;try{const r=await p(e,n);if(c=Math.ceil(r.total/f),c===0)return a.imageList.innerHTML="",a.loader.style.display="none",d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight",transitionIn:"bounceInDown",transitionOut:"fadeOutDown"});const s=u(r);a.imageList.innerHTML=s,new m(".images-list-item a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250,animationSpeed:300,widthRatio:1,heightRatio:.95,disableRightClick:!0}).refresh()}catch{}o.target.reset(),a.loader.style.display="none",a.loadBtn.style.display="block",y()});a.loadBtn.addEventListener("click",async o=>{o.preventDefault(),a.loading.style.display="block",a.loadBtn.style.display="none",n++;try{const e=await p(g,n),r=u(e);a.imageList.insertAdjacentHTML("beforeend",r),new m(".images-list-item a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250,animationSpeed:300,widthRatio:1,heightRatio:.95,disableRightClick:!0}).refresh(),b()}catch(e){console.log("Error: ",e)}a.loading.style.display="none",y()});function y(){n>=c?(a.loadBtn.style.display="none",n===c&&d.info({message:"We're sorry, but you've reached the end of search results."})):a.loadBtn.style.display="block"}function b(){const e=a.imageList.children[0].getBoundingClientRect().height;scrollBy({top:e*3,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
